#ifndef QS_COPYMGR_H_
#define QS_COPYMGR_H_
#include "vdevdefs.h"

#define SERVICE_ACTION_EXTENDED_COPY_LID1	0x00
#define SERVICE_ACTION_POPULATE_TOKEN		0x10
#define SERVICE_ACTION_WRITE_USING_TOKEN	0x11

#define SERVICE_ACTION_RECEIVE_COPY_STATUS_LID1		0x00
#define SERVICE_ACTION_RECEIVE_COPY_OPERATING_PARAMETERS	0x03
#define SERVICE_ACTION_RECEIVE_ROD_TOKEN_INFORMATION	0x07

#endif
